static_analyses:
  ignore_files: []
  ignore_unused_requirements: []
  ignore_missing_requirements:
    - configobj
downstream_dependencies:
- wc_kb
- wc_lang
email_notifications:
- karr@mssm.edu
- xzheng20@colby.edu
